# Настройки арбитражного бота MEXC vs DEX
# Автор: 24vasilekk (24vasilekk@gmail.com)
# Путь: config/settings.yaml
# ОБНОВЛЕН: Только новые токены (25 шт.), убраны стабильные

trading:
  # Основные параметры торговли
  min_spread_percent: 7.5        # Минимальный спред для входа в сделку (%)
  target_spread_percent: 1.5     # Целевой спред для выхода из сделки (%)  
  max_position_size: 5.10        # Фиксированный размер позиции в USDT
  test_mode: true                # Тестовый режим (true = без реальных сделок)
  leverage: 2                    # Кредитное плечо 2x
  
  # СПИСОК торговых пар - ТОЛЬКО НОВЫЕ ТОКЕНЫ (25 монет)
  symbols:
    # НОВЫЕ ДОБАВЛЕННЫЕ МОНЕТЫ (25 шт.)
    - "DIS/USDT"       # DIS
    - "UPTOP/USDT"     # UPTOP
    - "IRIS/USDT"      # IrisVirtual
    - "DUPE/USDT"      # DUPE
    - "TAG/USDT"       # TAG
    - "STARTUP/USDT"   # Startup
    - "GOG/USDT"       # GOG
    - "TGT/USDT"       # TGT
    - "AURASOL/USDT"   # AuraSol
    - "DINO/USDT"      # DINO
    - "ALTCOIN/USDT"   # AltCoin
    - "PEPE/USDT"      # PEPE
    - "ECHO/USDT"      # ECHO
    - "MANYU/USDT"     # Manyu
    - "APETH/USDT"     # apETH
    - "LABUBU/USDT"    # Labubu
    - "FART/USDT"      # FartBoy
    - "ELDE/USDT"      # ELDE
    - "GP/USDT"        # GP
    - "HOUSE/USDT"     # House
    - "ZEUS/USDT"      # ZeusETH
    - "BR/USDT"        # BR
    - "VSN/USDT"       # VSN
    - "RION/USDT"      # RION
    - "DEVVE/USDT"     # DEVVE

exchanges:
  # Настройки MEXC Futures
  mexc:
    name: "MEXC Futures"
    type: "futures" 
    fee_rate: 0.0002            # Комиссия 0.02% (maker/taker)
    leverage: 2                 # Кредитное плечо 2x
    
  # Источники цен DEX - ТОЛЬКО DEXSCREENER
  dex:
    # DexScreener - единственный источник
    dexscreener:
      url: "https://api.dexscreener.com/latest"
      fee_rate: 0.003           # Средняя комиссия DEX ~0.3%
      weight: 1.0               # Единственный источник

monitoring:
  price_update_interval: 1      # БЫСТРОЕ обновление цен каждую секунду
  health_check_interval: 30     # Интервал проверки здоровья системы (секунды)
  max_price_age: 2             # Максимальный возраст цены (2 секунды)
  reconnect_attempts: 5        # Больше попыток переподключения

risk_management:
  # УБРАНЫ ЛИМИТЫ ПОТЕРЬ по требованию
  max_daily_loss: 999999       # Лимиты убраны
  max_weekly_loss: 999999      # Лимиты убраны
  max_total_loss: 999999       # Лимиты убраны
  
  # Управление позициями
  max_positions: 10            # Больше одновременных позиций
  max_position_time: 3600      # Максимальное время удержания позиции (секунды)
  
  # АГРЕССИВНЫЕ стоп-лоссы и тейк-профиты
  stop_loss_percent: 50.0      # АГРЕССИВНЫЙ стоп-лосс 50%
  take_profit_percent: 20.0    # Увеличен тейк-профит до 20%
  
  # ФИКСИРОВАННЫЕ размеры позиций
  fixed_position_size: 5.10    # Фиксированный размер $5.10
  position_leverage: 2         # Плечо 2x

logging:
  level: "INFO"                # DEBUG, INFO, WARNING, ERROR
  file: "logs/arbitrage_bot.log"
  max_size: "10MB"
  backup_count: 5
  
  # Что логировать
  log_trades: true             # Логировать все сделки
  log_opportunities: true      # Логировать найденные возможности
  log_errors: true            # Логировать ошибки
  log_performance: true       # Логировать производительность

notifications:
  # Telegram уведомления (опционально)
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""
  
  # Email уведомления (опционально)
  email:
    enabled: false

database:
  # Настройки базы данных для хранения истории
  url: "sqlite:///data/arbitrage.db"
  
  # Что сохранять
  save_prices: true            # Сохранять историю цен
  save_trades: true            # Сохранять историю сделок
  save_opportunities: true     # Сохранять найденные возможности
  
  # Очистка старых данных
  cleanup_days: 30            # Удалять данные старше 30 дней